version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        runner: "web"
    command: bundle exec rackup --host 0.0.0.0 -p 3002
    ports:
      - '3002:3002'
    volumes:
      - .:/frontend-operator