development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 2
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 2
  username: postgres
  password: password
