require './config/environment'

run ApplicationController
use EnergyUsagesController
use PaymentHistoriesController
use PaymentsController
use AssignedFlightsController
use FlightsController
use FlightHistoriesController
