version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        runner: "web"
    command: bundle exec ruby server.rb
    ports:
      - '50059:50059'
    volumes:
      - .:/payment-service