version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        runner: "web"
    command: bundle exec ruby server.rb
    ports:
      - '50054:50054'
    volumes:
      - .:/energy-service