# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: battery.proto for package 'mobility.services'

require 'grpc'
require 'battery_pb'

module Mobility
  module Services
    module BatteryServices
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mobility.services.BatteryServices'

        rpc :ListBatterys, ::Mobility::Services::ListBatterysRequest, ::Mobility::Services::ListBatterysResponse
        rpc :GetBattery, ::Mobility::Services::GetBatteryRequest, ::Mobility::Services::GetBatteryResponse
        rpc :CreateBattery, ::Mobility::Services::CreateBatteryRequest, ::Mobility::Services::CreateBatteryResponse
        rpc :UpdateBattery, ::Mobility::Services::UpdateBatteryRequest, ::Mobility::Services::UpdateBatteryResponse
        rpc :DeleteBattery, ::Mobility::Services::DeleteBatteryRequest, ::Mobility::Services::DeleteBatteryResponse
        rpc :RetrieveBatteryChargePercentage, ::Mobility::Services::RetrieveBatteryChargePercentageRequest, ::Mobility::Services::RetrieveBatteryChargePercentageResponse
        rpc :SetBatteryChargePercentageThreshold, ::Mobility::Services::SetBatteryChargePercentageThresholdRequest, ::Mobility::Services::SetBatteryChargePercentageThresholdResponse
        rpc :CheckBatteryChargeBelowPercentageThreshold, ::Mobility::Services::CheckBatteryChargeBelowPercentageThresholdRequest, ::Mobility::Services::CheckBatteryChargeBelowPercentageThresholdResponse
        rpc :CheckBatteryIsAtStation, ::Mobility::Services::CheckBatteryIsAtStationRequest, ::Mobility::Services::CheckBatteryIsAtStationResponse
        rpc :CheckBatteryIsInFlight, ::Mobility::Services::CheckBatteryIsInFlightRequest, ::Mobility::Services::CheckBatteryIsInFlightResponse
        rpc :AssignBatteryToFlight, ::Mobility::Services::AssignBatteryToFlightRequest, ::Mobility::Services::AssignBatteryToFlightResponse
        rpc :AssignBatteryToMotorcycle, ::Mobility::Services::AssignBatteryToMotorcycleRequest, ::Mobility::Services::AssignBatteryToMotorcycleResponse
        rpc :RetrieveCurrentFlightForBattery, ::Mobility::Services::RetrieveCurrentFlightForBatteryRequest, ::Mobility::Services::RetrieveCurrentFlightForBatteryResponse
        rpc :RetrieveCurrentMotorcycleForBattery, ::Mobility::Services::RetrieveCurrentMotorcycleForBatteryRequest, ::Mobility::Services::RetrieveCurrentMotorcycleForBatteryResponse
        rpc :RetrieveCurrentLocationForBattery, ::Mobility::Services::RetrieveCurrentLocationForBatteryRequest, ::Mobility::Services::RetrieveCurrentLocationForBatteryResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
