# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battery.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("battery.proto", :syntax => :proto3) do
    add_message "mobility.services.Battery" do
      optional :issue_name, :string, 1
      optional :battery_id, :string, 2
      optional :type, :string, 3
      optional :created_at, :string, 4
      optional :modified_at, :string, 5
      optional :deleted_at, :string, 6
      optional :charge_percentage, :int32, 7
      optional :below_threshold, :bool, 8
      optional :at_station, :bool, 9
      optional :in_flight, :bool, 10
      optional :flight_id, :string, 11
    end
    add_message "mobility.services.BatterysList" do
      repeated :batterys, :message, 1, "mobility.services.Battery"
    end
    add_message "mobility.services.BatterySuccessResponse" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.BatteryErrorResponse" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListBatterysRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListBatterysResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :batterys_list, :message, 3, "mobility.services.BatterysList"
      end
    end
    add_message "mobility.services.GetBatteryRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.GetBatteryResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :battery, :message, 3, "mobility.services.Battery"
      end
    end
    add_message "mobility.services.CreateBatteryRequest" do
      optional :battery, :message, 1, "mobility.services.Battery"
    end
    add_message "mobility.services.CreateBatteryResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :battery, :message, 3, "mobility.services.Battery"
      end
    end
    add_message "mobility.services.UpdateBatteryRequest" do
      optional :battery, :message, 1, "mobility.services.Battery"
    end
    add_message "mobility.services.UpdateBatteryResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :battery, :message, 3, "mobility.services.Battery"
      end
    end
    add_message "mobility.services.DeleteBatteryRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.DeleteBatteryResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :success, :message, 3, "mobility.services.BatterySuccessResponse"
      end
    end
    add_message "mobility.services.RetrieveBatteryChargePercentageRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.RetrieveBatteryChargePercentageResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :charge_percentage, :int32, 3
      end
    end
    add_message "mobility.services.SetBatteryChargePercentageThresholdRequest" do
      optional :battery_id, :string, 1
      optional :charge_percentage, :int32, 2
    end
    add_message "mobility.services.SetBatteryChargePercentageThresholdResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :success, :message, 3, "mobility.services.BatterySuccessResponse"
      end
    end
    add_message "mobility.services.CheckBatteryChargeBelowPercentageThresholdRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.CheckBatteryChargeBelowPercentageThresholdResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :below_threshold, :bool, 3
      end
    end
    add_message "mobility.services.CheckBatteryIsAtStationRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.CheckBatteryIsAtStationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :at_station, :bool, 3
      end
    end
    add_message "mobility.services.CheckBatteryIsInFlightRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.CheckBatteryIsInFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :in_flight, :bool, 3
      end
    end
    add_message "mobility.services.AssignBatteryToFlightRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.AssignBatteryToFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :success, :message, 3, "mobility.services.BatterySuccessResponse"
      end
    end
    add_message "mobility.services.AssignBatteryToMotorcycleRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.AssignBatteryToMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :success, :message, 3, "mobility.services.BatterySuccessResponse"
      end
    end
    add_message "mobility.services.RetrieveCurrentFlightForBatteryRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.RetrieveCurrentFlightForBatteryResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :flight_id, :string, 3
      end
    end
    add_message "mobility.services.RetrieveCurrentMotorcycleForBatteryRequest" do
    end
    add_message "mobility.services.RetrieveCurrentMotorcycleForBatteryResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :motorcycle_id, :string, 3
      end
    end
    add_message "mobility.services.RetrieveCurrentLocationForBatteryRequest" do
    end
    add_message "mobility.services.RetrieveCurrentLocationForBatteryResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.BatteryErrorResponse"
        optional :location_id, :string, 3
      end
    end
  end
end

module Mobility
  module Services
    Battery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Battery").msgclass
    BatterysList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.BatterysList").msgclass
    BatterySuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.BatterySuccessResponse").msgclass
    BatteryErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.BatteryErrorResponse").msgclass
    ListBatterysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListBatterysRequest").msgclass
    ListBatterysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListBatterysResponse").msgclass
    GetBatteryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetBatteryRequest").msgclass
    GetBatteryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetBatteryResponse").msgclass
    CreateBatteryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateBatteryRequest").msgclass
    CreateBatteryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateBatteryResponse").msgclass
    UpdateBatteryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateBatteryRequest").msgclass
    UpdateBatteryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateBatteryResponse").msgclass
    DeleteBatteryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteBatteryRequest").msgclass
    DeleteBatteryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteBatteryResponse").msgclass
    RetrieveBatteryChargePercentageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveBatteryChargePercentageRequest").msgclass
    RetrieveBatteryChargePercentageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveBatteryChargePercentageResponse").msgclass
    SetBatteryChargePercentageThresholdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SetBatteryChargePercentageThresholdRequest").msgclass
    SetBatteryChargePercentageThresholdResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SetBatteryChargePercentageThresholdResponse").msgclass
    CheckBatteryChargeBelowPercentageThresholdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CheckBatteryChargeBelowPercentageThresholdRequest").msgclass
    CheckBatteryChargeBelowPercentageThresholdResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CheckBatteryChargeBelowPercentageThresholdResponse").msgclass
    CheckBatteryIsAtStationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CheckBatteryIsAtStationRequest").msgclass
    CheckBatteryIsAtStationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CheckBatteryIsAtStationResponse").msgclass
    CheckBatteryIsInFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CheckBatteryIsInFlightRequest").msgclass
    CheckBatteryIsInFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CheckBatteryIsInFlightResponse").msgclass
    AssignBatteryToFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AssignBatteryToFlightRequest").msgclass
    AssignBatteryToFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AssignBatteryToFlightResponse").msgclass
    AssignBatteryToMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AssignBatteryToMotorcycleRequest").msgclass
    AssignBatteryToMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AssignBatteryToMotorcycleResponse").msgclass
    RetrieveCurrentFlightForBatteryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentFlightForBatteryRequest").msgclass
    RetrieveCurrentFlightForBatteryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentFlightForBatteryResponse").msgclass
    RetrieveCurrentMotorcycleForBatteryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentMotorcycleForBatteryRequest").msgclass
    RetrieveCurrentMotorcycleForBatteryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentMotorcycleForBatteryResponse").msgclass
    RetrieveCurrentLocationForBatteryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentLocationForBatteryRequest").msgclass
    RetrieveCurrentLocationForBatteryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentLocationForBatteryResponse").msgclass
  end
end
