# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: distance.proto for package 'mobility.services'

require 'grpc'
require_relative './distance_pb'

module Mobility
  module Services
    module DistanceServices
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mobility.services.DistanceServices'

        rpc :ListDistances, ::Mobility::Services::ListDistancesRequest, ::Mobility::Services::ListDistancesResponse
        rpc :GetDistance, ::Mobility::Services::GetDistanceRequest, ::Mobility::Services::GetDistanceResponse
        rpc :CreateDistance, ::Mobility::Services::CreateDistanceRequest, ::Mobility::Services::CreateDistanceResponse
        rpc :UpdateDistance, ::Mobility::Services::UpdateDistanceRequest, ::Mobility::Services::UpdateDistanceResponse
        rpc :DeleteDistance, ::Mobility::Services::DeleteDistanceRequest, ::Mobility::Services::DeleteDistanceResponse
        rpc :StartDistanceDataStreamForFlightID, ::Mobility::Services::StartDistanceDataStreamForFlightIDRequest, ::Mobility::Services::StartDistanceDataStreamForFlightIDResponse
        rpc :StopDistanceDataStreamForFlightID, ::Mobility::Services::StopDistanceDataStreamForFlightIDRequest, ::Mobility::Services::StopDistanceDataStreamForFlightIDResponse
        rpc :AggregateDistanceDataStreamForFlightID, ::Mobility::Services::AggregateDistanceDataStreamForFlightIDRequest, ::Mobility::Services::AggregateDistanceDataStreamForFlightIDResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
