# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distance.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("distance.proto", :syntax => :proto3) do
    add_message "mobility.services.Distance" do
      optional :distance_id, :string, 1
      optional :flight_id, :string, 2
      optional :location_id, :string, 3
      optional :distance_delta, :string, 4
      optional :created_at, :string, 5
      optional :modified_at, :string, 6
      optional :deleted_at, :string, 7
    end
    add_message "mobility.services.DistancesList" do
      repeated :distances, :message, 1, "mobility.services.Distance"
    end
    add_message "mobility.services.Success" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.Error" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListDistancesRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListDistancesResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :distances_list, :message, 3, "mobility.services.DistancesList"
      end
    end
    add_message "mobility.services.GetDistanceRequest" do
      optional :distance_id, :string, 1
    end
    add_message "mobility.services.GetDistanceResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :distance, :message, 3, "mobility.services.Distance"
      end
    end
    add_message "mobility.services.CreateDistanceRequest" do
      optional :distance, :message, 1, "mobility.services.Distance"
    end
    add_message "mobility.services.CreateDistanceResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :distance, :message, 3, "mobility.services.Distance"
      end
    end
    add_message "mobility.services.UpdateDistanceRequest" do
      optional :distance, :message, 1, "mobility.services.Distance"
    end
    add_message "mobility.services.UpdateDistanceResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :distance, :message, 3, "mobility.services.Distance"
      end
    end
    add_message "mobility.services.DeleteDistanceRequest" do
      optional :distance_id, :string, 1
    end
    add_message "mobility.services.DeleteDistanceResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.StartDistanceDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.StartDistanceDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.StopDistanceDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.StopDistanceDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.AggregateDistanceDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.AggregateDistanceDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
  end
end

module Mobility
  module Services
    Distance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Distance").msgclass
    DistancesList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DistancesList").msgclass
    Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Success").msgclass
    Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Error").msgclass
    ListDistancesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListDistancesRequest").msgclass
    ListDistancesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListDistancesResponse").msgclass
    GetDistanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetDistanceRequest").msgclass
    GetDistanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetDistanceResponse").msgclass
    CreateDistanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateDistanceRequest").msgclass
    CreateDistanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateDistanceResponse").msgclass
    UpdateDistanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateDistanceRequest").msgclass
    UpdateDistanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateDistanceResponse").msgclass
    DeleteDistanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteDistanceRequest").msgclass
    DeleteDistanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteDistanceResponse").msgclass
    StartDistanceDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StartDistanceDataStreamForFlightIDRequest").msgclass
    StartDistanceDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StartDistanceDataStreamForFlightIDResponse").msgclass
    StopDistanceDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StopDistanceDataStreamForFlightIDRequest").msgclass
    StopDistanceDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StopDistanceDataStreamForFlightIDResponse").msgclass
    AggregateDistanceDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AggregateDistanceDataStreamForFlightIDRequest").msgclass
    AggregateDistanceDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AggregateDistanceDataStreamForFlightIDResponse").msgclass
  end
end
