# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: driver.proto for package 'mobility.protos.driver'

require 'grpc'
require 'driver_pb'

module Mobility
  module Protos
    module Driver
      module DriverServices
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'mobility.protos.driver.DriverServices'

          rpc :ListDrivers, ::Mobility::Protos::Driver::ListDriversRequest, ::Mobility::Protos::Driver::ListDriversResponse
          rpc :GetDriver, ::Mobility::Protos::Driver::GetDriverRequest, ::Mobility::Protos::Driver::GetDriverResponse
          rpc :CreateDriver, ::Mobility::Protos::Driver::CreateDriverRequest, ::Mobility::Protos::Driver::CreateDriverResponse
          rpc :UpdateDriver, ::Mobility::Protos::Driver::UpdateDriverRequest, ::Mobility::Protos::Driver::UpdateDriverResponse
          rpc :DeleteDriver, ::Mobility::Protos::Driver::DeleteDriverRequest, ::Mobility::Protos::Driver::DeleteDriverResponse
          rpc :AssignFlightToDriver, ::Mobility::Protos::Driver::AssignFlightToDriverRequest, ::Mobility::Protos::Driver::AssignFlightToDriverResponse
          rpc :RetrieveFlightAssignedToDriver, ::Mobility::Protos::Driver::RetrieveFlightAssignedToDriverRequest, ::Mobility::Protos::Driver::RetrieveFlightAssignedToDriverResponse
          rpc :RetrieveEnergyUsageByDriver, ::Mobility::Protos::Driver::RetrieveEnergyUsageByDriverRequest, ::Mobility::Protos::Driver::RetrieveEnergyUsageByDriverResponse
          rpc :RetrieveEnergyUsageByDriverForFlight, ::Mobility::Protos::Driver::RetrieveEnergyUsageByDriverForFlightRequest, ::Mobility::Protos::Driver::RetrieveEnergyUsageByDriverForFlightResponse
          rpc :RetrieveDistanceCoveredByDriver, ::Mobility::Protos::Driver::RetrieveDistanceCoveredByDriverRequest, ::Mobility::Protos::Driver::RetrieveDistanceCoveredByDriverResponse
          rpc :RetrieveDistanceCoveredByDriverForFlight, ::Mobility::Protos::Driver::RetrieveDistanceCoveredByDriverForFlightRequest, ::Mobility::Protos::Driver::RetrieveDistanceCoveredByDriverForFlightResponse
          rpc :MakePaymentByDriverForFlight, ::Mobility::Protos::Driver::MakePaymentByDriverForFlightRequest, ::Mobility::Protos::Driver::MakePaymentByDriverResponse
          rpc :GetPaymentByDriverForFlight, ::Mobility::Protos::Driver::GetPaymentByDriverForFlightRequest, ::Mobility::Protos::Driver::GetPaymentByDriverResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
