# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("driver.proto", :syntax => :proto3) do
    add_message "mobility.services.Driver" do
      optional :driver_id, :string, 1
      optional :name, :string, 2
      optional :identification, :string, 3
      optional :phone_number, :string, 4
      optional :created_at, :string, 5
      optional :modified_at, :string, 6
      optional :deleted_at, :string, 7
    end
    add_message "mobility.services.DriversList" do
      repeated :drivers, :message, 1, "mobility.services.Driver"
    end
    add_message "mobility.services.DriverSuccessResponse" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.DriverErrorResponse" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListDriversRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListDriversResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :drivers_list, :message, 3, "mobility.services.DriversList"
      end
    end
    add_message "mobility.services.GetDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.services.GetDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :driver, :message, 3, "mobility.services.Driver"
      end
    end
    add_message "mobility.services.CreateDriverRequest" do
      optional :driver, :message, 1, "mobility.services.Driver"
    end
    add_message "mobility.services.CreateDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :driver, :message, 3, "mobility.services.Driver"
      end
    end
    add_message "mobility.services.UpdateDriverRequest" do
      optional :driver, :message, 1, "mobility.services.Driver"
    end
    add_message "mobility.services.UpdateDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :driver, :message, 3, "mobility.services.Driver"
      end
    end
    add_message "mobility.services.DeleteDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.services.DeleteDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :success, :message, 3, "mobility.services.DriverSuccessResponse"
      end
    end
    add_message "mobility.services.AssignFlightToDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.services.AssignFlightToDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :success, :message, 3, "mobility.services.DriverSuccessResponse"
      end
    end
    add_message "mobility.services.RetrieveFlightAssignedToDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.services.RetrieveFlightAssignedToDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :current_flight_id, :string, 3
      end
    end
    add_message "mobility.services.RetrieveEnergyUsageByDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.services.RetrieveEnergyUsageByDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :total_energy_delta, :int32, 3
      end
    end
    add_message "mobility.services.RetrieveEnergyUsageByDriverForFlightRequest" do
      optional :driver_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.services.RetrieveEnergyUsageByDriverForFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :flight_total_energy_delta, :int32, 3
      end
    end
    add_message "mobility.services.RetrieveDistanceCoveredByDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.services.RetrieveDistanceCoveredByDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :total_distance_delta, :int32, 3
      end
    end
    add_message "mobility.services.RetrieveDistanceCoveredByDriverForFlightRequest" do
      optional :driver_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.services.RetrieveDistanceCoveredByDriverForFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :flight_total_distance_delta, :int32, 3
      end
    end
    add_message "mobility.services.MakePaymentByDriverForFlightRequest" do
      optional :driver_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.services.MakePaymentByDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :success, :message, 3, "mobility.services.DriverSuccessResponse"
      end
    end
    add_message "mobility.services.GetPaymentByDriverForFlightRequest" do
      optional :driver_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.services.GetPaymentByDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.DriverErrorResponse"
        optional :payment_id, :string, 3
      end
    end
  end
end

module Mobility
  module Services
    Driver = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Driver").msgclass
    DriversList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DriversList").msgclass
    DriverSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DriverSuccessResponse").msgclass
    DriverErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DriverErrorResponse").msgclass
    ListDriversRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListDriversRequest").msgclass
    ListDriversResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListDriversResponse").msgclass
    GetDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetDriverRequest").msgclass
    GetDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetDriverResponse").msgclass
    CreateDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateDriverRequest").msgclass
    CreateDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateDriverResponse").msgclass
    UpdateDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateDriverRequest").msgclass
    UpdateDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateDriverResponse").msgclass
    DeleteDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteDriverRequest").msgclass
    DeleteDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteDriverResponse").msgclass
    AssignFlightToDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AssignFlightToDriverRequest").msgclass
    AssignFlightToDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AssignFlightToDriverResponse").msgclass
    RetrieveFlightAssignedToDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveFlightAssignedToDriverRequest").msgclass
    RetrieveFlightAssignedToDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveFlightAssignedToDriverResponse").msgclass
    RetrieveEnergyUsageByDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveEnergyUsageByDriverRequest").msgclass
    RetrieveEnergyUsageByDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveEnergyUsageByDriverResponse").msgclass
    RetrieveEnergyUsageByDriverForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveEnergyUsageByDriverForFlightRequest").msgclass
    RetrieveEnergyUsageByDriverForFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveEnergyUsageByDriverForFlightResponse").msgclass
    RetrieveDistanceCoveredByDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveDistanceCoveredByDriverRequest").msgclass
    RetrieveDistanceCoveredByDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveDistanceCoveredByDriverResponse").msgclass
    RetrieveDistanceCoveredByDriverForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveDistanceCoveredByDriverForFlightRequest").msgclass
    RetrieveDistanceCoveredByDriverForFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveDistanceCoveredByDriverForFlightResponse").msgclass
    MakePaymentByDriverForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.MakePaymentByDriverForFlightRequest").msgclass
    MakePaymentByDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.MakePaymentByDriverResponse").msgclass
    GetPaymentByDriverForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetPaymentByDriverForFlightRequest").msgclass
    GetPaymentByDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetPaymentByDriverResponse").msgclass
  end
end
