# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("driver.proto", :syntax => :proto3) do
    add_message "mobility.protos.driver.Driver" do
      optional :driver_id, :string, 1
      optional :name, :string, 2
      optional :identification, :string, 3
      optional :phone_number, :string, 4
      optional :created_at, :string, 5
      optional :modified_at, :string, 6
      optional :deleted_at, :string, 7
    end
    add_message "mobility.protos.driver.DriversList" do
      repeated :drivers, :message, 1, "mobility.protos.driver.Driver"
    end
    add_message "mobility.protos.driver.Success" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.protos.driver.Error" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.protos.driver.ListDriversRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.protos.driver.ListDriversResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :drivers_list, :message, 3, "mobility.protos.driver.DriversList"
      end
    end
    add_message "mobility.protos.driver.GetDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.protos.driver.GetDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :driver, :message, 3, "mobility.protos.driver.Driver"
      end
    end
    add_message "mobility.protos.driver.CreateDriverRequest" do
      optional :driver, :message, 1, "mobility.protos.driver.Driver"
    end
    add_message "mobility.protos.driver.CreateDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :driver, :message, 3, "mobility.protos.driver.Driver"
      end
    end
    add_message "mobility.protos.driver.UpdateDriverRequest" do
      optional :driver, :message, 1, "mobility.protos.driver.Driver"
    end
    add_message "mobility.protos.driver.UpdateDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :driver, :message, 3, "mobility.protos.driver.Driver"
      end
    end
    add_message "mobility.protos.driver.DeleteDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.protos.driver.DeleteDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :success, :message, 3, "mobility.protos.driver.Success"
      end
    end
    add_message "mobility.protos.driver.AssignFlightToDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.protos.driver.AssignFlightToDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :success, :message, 3, "mobility.protos.driver.Success"
      end
    end
    add_message "mobility.protos.driver.RetrieveFlightAssignedToDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.protos.driver.RetrieveFlightAssignedToDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :current_flight_id, :string, 3
      end
    end
    add_message "mobility.protos.driver.RetrieveEnergyUsageByDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.protos.driver.RetrieveEnergyUsageByDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :total_energy_delta, :int32, 3
      end
    end
    add_message "mobility.protos.driver.RetrieveEnergyUsageByDriverForFlightRequest" do
      optional :driver_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.protos.driver.RetrieveEnergyUsageByDriverForFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :flight_total_energy_delta, :int32, 3
      end
    end
    add_message "mobility.protos.driver.RetrieveDistanceCoveredByDriverRequest" do
      optional :driver_id, :string, 1
    end
    add_message "mobility.protos.driver.RetrieveDistanceCoveredByDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :total_distance_delta, :int32, 3
      end
    end
    add_message "mobility.protos.driver.RetrieveDistanceCoveredByDriverForFlightRequest" do
      optional :driver_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.protos.driver.RetrieveDistanceCoveredByDriverForFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :flight_total_distance_delta, :int32, 3
      end
    end
    add_message "mobility.protos.driver.MakePaymentByDriverForFlightRequest" do
      optional :driver_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.protos.driver.MakePaymentByDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :success, :message, 3, "mobility.protos.driver.Success"
      end
    end
    add_message "mobility.protos.driver.GetPaymentByDriverForFlightRequest" do
      optional :driver_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.protos.driver.GetPaymentByDriverResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.protos.driver.Error"
        optional :payment_id, :string, 3
      end
    end
  end
end

module Mobility
  module Protos
    module Driver
      Driver = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.Driver").msgclass
      DriversList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.DriversList").msgclass
      Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.Success").msgclass
      Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.Error").msgclass
      ListDriversRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.ListDriversRequest").msgclass
      ListDriversResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.ListDriversResponse").msgclass
      GetDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.GetDriverRequest").msgclass
      GetDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.GetDriverResponse").msgclass
      CreateDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.CreateDriverRequest").msgclass
      CreateDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.CreateDriverResponse").msgclass
      UpdateDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.UpdateDriverRequest").msgclass
      UpdateDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.UpdateDriverResponse").msgclass
      DeleteDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.DeleteDriverRequest").msgclass
      DeleteDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.DeleteDriverResponse").msgclass
      AssignFlightToDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.AssignFlightToDriverRequest").msgclass
      AssignFlightToDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.AssignFlightToDriverResponse").msgclass
      RetrieveFlightAssignedToDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveFlightAssignedToDriverRequest").msgclass
      RetrieveFlightAssignedToDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveFlightAssignedToDriverResponse").msgclass
      RetrieveEnergyUsageByDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveEnergyUsageByDriverRequest").msgclass
      RetrieveEnergyUsageByDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveEnergyUsageByDriverResponse").msgclass
      RetrieveEnergyUsageByDriverForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveEnergyUsageByDriverForFlightRequest").msgclass
      RetrieveEnergyUsageByDriverForFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveEnergyUsageByDriverForFlightResponse").msgclass
      RetrieveDistanceCoveredByDriverRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveDistanceCoveredByDriverRequest").msgclass
      RetrieveDistanceCoveredByDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveDistanceCoveredByDriverResponse").msgclass
      RetrieveDistanceCoveredByDriverForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveDistanceCoveredByDriverForFlightRequest").msgclass
      RetrieveDistanceCoveredByDriverForFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.RetrieveDistanceCoveredByDriverForFlightResponse").msgclass
      MakePaymentByDriverForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.MakePaymentByDriverForFlightRequest").msgclass
      MakePaymentByDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.MakePaymentByDriverResponse").msgclass
      GetPaymentByDriverForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.GetPaymentByDriverForFlightRequest").msgclass
      GetPaymentByDriverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.protos.driver.GetPaymentByDriverResponse").msgclass
    end
  end
end
