# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: driver.proto for package 'mobility.services'

require 'grpc'
require_relative 'driver_pb'

module Mobility
  module Services
    module DriverServices
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mobility.services.DriverServices'

        rpc :ListDrivers, ::Mobility::Services::ListDriversRequest, ::Mobility::Services::ListDriversResponse
        rpc :GetDriver, ::Mobility::Services::GetDriverRequest, ::Mobility::Services::GetDriverResponse
        rpc :CreateDriver, ::Mobility::Services::CreateDriverRequest, ::Mobility::Services::CreateDriverResponse
        rpc :UpdateDriver, ::Mobility::Services::UpdateDriverRequest, ::Mobility::Services::UpdateDriverResponse
        rpc :DeleteDriver, ::Mobility::Services::DeleteDriverRequest, ::Mobility::Services::DeleteDriverResponse
        rpc :AssignFlightToDriver, ::Mobility::Services::AssignFlightToDriverRequest, ::Mobility::Services::AssignFlightToDriverResponse
        rpc :RetrieveFlightAssignedToDriver, ::Mobility::Services::RetrieveFlightAssignedToDriverRequest, ::Mobility::Services::RetrieveFlightAssignedToDriverResponse
        rpc :RetrieveEnergyUsageByDriver, ::Mobility::Services::RetrieveEnergyUsageByDriverRequest, ::Mobility::Services::RetrieveEnergyUsageByDriverResponse
        rpc :RetrieveEnergyUsageByDriverForFlight, ::Mobility::Services::RetrieveEnergyUsageByDriverForFlightRequest, ::Mobility::Services::RetrieveEnergyUsageByDriverForFlightResponse
        rpc :RetrieveDistanceCoveredByDriver, ::Mobility::Services::RetrieveDistanceCoveredByDriverRequest, ::Mobility::Services::RetrieveDistanceCoveredByDriverResponse
        rpc :RetrieveDistanceCoveredByDriverForFlight, ::Mobility::Services::RetrieveDistanceCoveredByDriverForFlightRequest, ::Mobility::Services::RetrieveDistanceCoveredByDriverForFlightResponse
        rpc :MakePaymentByDriverForFlight, ::Mobility::Services::MakePaymentByDriverForFlightRequest, ::Mobility::Services::MakePaymentByDriverResponse
        rpc :GetPaymentByDriverForFlight, ::Mobility::Services::GetPaymentByDriverForFlightRequest, ::Mobility::Services::GetPaymentByDriverResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
