# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: energy.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("energy.proto", :syntax => :proto3) do
    add_message "mobility.services.Energy" do
      optional :energy_id, :string, 1
      optional :flight_id, :string, 2
      optional :location_id, :string, 3
      optional :energy_delta, :int32, 4
      optional :created_at, :string, 5
      optional :modified_on, :string, 6
      optional :ended_at, :string, 7
    end
    add_message "mobility.services.EnergysList" do
      repeated :energys, :message, 1, "mobility.services.Energy"
    end
    add_message "mobility.services.Success" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.Error" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListEnergysRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListEnergysResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :energys_list, :message, 3, "mobility.services.EnergysList"
      end
    end
    add_message "mobility.services.GetEnergyRequest" do
      optional :energy_id, :string, 1
    end
    add_message "mobility.services.GetEnergyResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :energy, :message, 3, "mobility.services.Energy"
      end
    end
    add_message "mobility.services.CreateEnergyRequest" do
      optional :energy, :message, 1, "mobility.services.Energy"
    end
    add_message "mobility.services.CreateEnergyResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :energy, :message, 3, "mobility.services.Energy"
      end
    end
    add_message "mobility.services.UpdateEnergyRequest" do
      optional :energy, :message, 1, "mobility.services.Energy"
    end
    add_message "mobility.services.UpdateEnergyResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :energy, :message, 3, "mobility.services.Energy"
      end
    end
    add_message "mobility.services.DeleteEnergyRequest" do
      optional :energy_id, :string, 1
    end
    add_message "mobility.services.DeleteEnergyResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.StartEnergyDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.StartEnergyDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.StopEnergyDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.StopEnergyDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.AggregateEnergyDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.AggregateEnergyDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
  end
end

module Mobility
  module Services
    Energy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Energy").msgclass
    EnergysList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.EnergysList").msgclass
    Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Success").msgclass
    Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Error").msgclass
    ListEnergysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListEnergysRequest").msgclass
    ListEnergysResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListEnergysResponse").msgclass
    GetEnergyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetEnergyRequest").msgclass
    GetEnergyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetEnergyResponse").msgclass
    CreateEnergyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateEnergyRequest").msgclass
    CreateEnergyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateEnergyResponse").msgclass
    UpdateEnergyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateEnergyRequest").msgclass
    UpdateEnergyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateEnergyResponse").msgclass
    DeleteEnergyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteEnergyRequest").msgclass
    DeleteEnergyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteEnergyResponse").msgclass
    StartEnergyDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StartEnergyDataStreamForFlightIDRequest").msgclass
    StartEnergyDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StartEnergyDataStreamForFlightIDResponse").msgclass
    StopEnergyDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StopEnergyDataStreamForFlightIDRequest").msgclass
    StopEnergyDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StopEnergyDataStreamForFlightIDResponse").msgclass
    AggregateEnergyDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AggregateEnergyDataStreamForFlightIDRequest").msgclass
    AggregateEnergyDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AggregateEnergyDataStreamForFlightIDResponse").msgclass
  end
end
