# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: location.proto for package 'mobility.services'

require 'grpc'
require_relative './location_pb'

module Mobility
  module Services
    module LocationServices
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mobility.services.LocationServices'

        rpc :ListLocations, ::Mobility::Services::ListLocationsRequest, ::Mobility::Services::ListLocationsResponse
        rpc :GetLocation, ::Mobility::Services::GetLocationRequest, ::Mobility::Services::GetLocationResponse
        rpc :CreateLocation, ::Mobility::Services::CreateLocationRequest, ::Mobility::Services::CreateLocationResponse
        rpc :UpdateLocation, ::Mobility::Services::UpdateLocationRequest, ::Mobility::Services::UpdateLocationResponse
        rpc :DeleteLocation, ::Mobility::Services::DeleteLocationRequest, ::Mobility::Services::DeleteLocationResponse
        rpc :StartLocationDataStreamForFlightID, ::Mobility::Services::StartLocationDataStreamForFlightIDRequest, ::Mobility::Services::StartLocationDataStreamForFlightIDResponse
        rpc :StopLocationDataStreamForFlightID, ::Mobility::Services::StopLocationDataStreamForFlightIDRequest, ::Mobility::Services::StopLocationDataStreamForFlightIDResponse
        rpc :AggregateLocationDataStreamForFlightID, ::Mobility::Services::AggregateLocationDataStreamForFlightIDRequest, ::Mobility::Services::AggregateLocationDataStreamForFlightIDResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
