# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("location.proto", :syntax => :proto3) do
    add_message "mobility.services.Location" do
      optional :location_id, :string, 1
      optional :flight_id, :string, 2
      optional :latitude, :string, 3
      optional :longitude, :string, 4
      optional :motorcycle_id, :string, 5
      optional :created_at, :string, 6
      optional :modified_on, :string, 7
      optional :ended_at, :string, 8
    end
    add_message "mobility.services.LocationsList" do
      repeated :locations, :message, 1, "mobility.services.Location"
    end
    add_message "mobility.services.LocationSuccessResponse" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.LocationErrorResponse" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListLocationsRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListLocationsResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.LocationErrorResponse"
        optional :locations_list, :message, 3, "mobility.services.LocationsList"
      end
    end
    add_message "mobility.services.GetLocationRequest" do
      optional :location_id, :string, 1
    end
    add_message "mobility.services.GetLocationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.LocationErrorResponse"
        optional :location, :message, 3, "mobility.services.Location"
      end
    end
    add_message "mobility.services.CreateLocationRequest" do
      optional :location, :message, 1, "mobility.services.Location"
    end
    add_message "mobility.services.CreateLocationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.LocationErrorResponse"
        optional :location, :message, 3, "mobility.services.Location"
      end
    end
    add_message "mobility.services.UpdateLocationRequest" do
      optional :location, :message, 1, "mobility.services.Location"
    end
    add_message "mobility.services.UpdateLocationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.LocationErrorResponse"
        optional :location, :message, 3, "mobility.services.Location"
      end
    end
    add_message "mobility.services.DeleteLocationRequest" do
      optional :location_id, :string, 1
    end
    add_message "mobility.services.DeleteLocationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.LocationErrorResponse"
        optional :success, :message, 3, "mobility.services.LocationSuccessResponse"
      end
    end
    add_message "mobility.services.StartLocationDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.StartLocationDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.LocationErrorResponse"
        optional :success, :message, 3, "mobility.services.LocationSuccessResponse"
      end
    end
    add_message "mobility.services.StopLocationDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.StopLocationDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.LocationErrorResponse"
        optional :success, :message, 3, "mobility.services.LocationSuccessResponse"
      end
    end
    add_message "mobility.services.AggregateLocationDataStreamForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.AggregateLocationDataStreamForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.LocationErrorResponse"
        optional :success, :message, 3, "mobility.services.LocationSuccessResponse"
      end
    end
  end
end

module Mobility
  module Services
    Location = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Location").msgclass
    LocationsList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.LocationsList").msgclass
    LocationSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.LocationSuccessResponse").msgclass
    LocationErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.LocationErrorResponse").msgclass
    ListLocationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListLocationsRequest").msgclass
    ListLocationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListLocationsResponse").msgclass
    GetLocationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetLocationRequest").msgclass
    GetLocationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetLocationResponse").msgclass
    CreateLocationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateLocationRequest").msgclass
    CreateLocationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateLocationResponse").msgclass
    UpdateLocationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateLocationRequest").msgclass
    UpdateLocationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateLocationResponse").msgclass
    DeleteLocationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteLocationRequest").msgclass
    DeleteLocationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteLocationResponse").msgclass
    StartLocationDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StartLocationDataStreamForFlightIDRequest").msgclass
    StartLocationDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StartLocationDataStreamForFlightIDResponse").msgclass
    StopLocationDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StopLocationDataStreamForFlightIDRequest").msgclass
    StopLocationDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StopLocationDataStreamForFlightIDResponse").msgclass
    AggregateLocationDataStreamForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AggregateLocationDataStreamForFlightIDRequest").msgclass
    AggregateLocationDataStreamForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AggregateLocationDataStreamForFlightIDResponse").msgclass
  end
end
