# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motorcycle.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("motorcycle.proto", :syntax => :proto3) do
    add_message "mobility.services.Motorcycle" do
      optional :issue_name, :string, 1
      optional :motorcycle_id, :string, 2
      optional :type, :string, 3
      optional :created_at, :string, 4
      optional :modified_at, :string, 5
      optional :deleted_at, :string, 6
      optional :current_battery_id, :string, 7
      optional :current_flight_id, :string, 8
      optional :current_location_id, :string, 9
      optional :current_distance_id, :string, 10
    end
    add_message "mobility.services.MotorcyclesList" do
      repeated :motorcycles, :message, 1, "mobility.services.Motorcycle"
    end
    add_message "mobility.services.MotorcycleSuccessResponse" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.MotorcycleErrorResponse" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListMotorcyclesRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListMotorcyclesResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :motorcycles_list, :message, 3, "mobility.services.MotorcyclesList"
      end
    end
    add_message "mobility.services.GetMotorcycleRequest" do
      optional :motorcycle_id, :string, 1
    end
    add_message "mobility.services.GetMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :motorcycle, :message, 3, "mobility.services.Motorcycle"
      end
    end
    add_message "mobility.services.CreateMotorcycleRequest" do
      optional :motorcycle, :message, 1, "mobility.services.Motorcycle"
    end
    add_message "mobility.services.CreateMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :motorcycle, :message, 3, "mobility.services.Motorcycle"
      end
    end
    add_message "mobility.services.UpdateMotorcycleRequest" do
      optional :motorcycle, :message, 1, "mobility.services.Motorcycle"
    end
    add_message "mobility.services.UpdateMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :motorcycle, :message, 3, "mobility.services.Motorcycle"
      end
    end
    add_message "mobility.services.DeleteMotorcycleRequest" do
      optional :motorcycle_id, :string, 1
    end
    add_message "mobility.services.DeleteMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :success, :message, 3, "mobility.services.MotorcycleSuccessResponse"
      end
    end
    add_message "mobility.services.ReceiveBatteryForMotorcycleRequest" do
      optional :motorcycle_id, :string, 1
    end
    add_message "mobility.services.ReceiveBatteryForMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :current_battery_id, :string, 3
      end
    end
    add_message "mobility.services.ReturnBatteryForMotorcycleRequest" do
      optional :motorcycle_id, :string, 1
      optional :battery_id, :string, 2
    end
    add_message "mobility.services.ReturnBatteryForMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :success, :message, 3, "mobility.services.MotorcycleSuccessResponse"
      end
    end
    add_message "mobility.services.AssignFlightForMotorcycleRequest" do
      optional :motorcycle_id, :string, 1
    end
    add_message "mobility.services.AssignFlightForMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :success, :message, 3, "mobility.services.MotorcycleSuccessResponse"
      end
    end
    add_message "mobility.services.RetrieveCurrentFlightForMotorcycleRequest" do
      optional :motorcycle_id, :string, 1
    end
    add_message "mobility.services.RetrieveCurrentFlightForMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :current_flight_id, :string, 3
      end
    end
    add_message "mobility.services.RetrieveCurrentLocationForMotorcycleRequest" do
      optional :motorcycle_id, :string, 1
    end
    add_message "mobility.services.RetrieveCurrentLocationForMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :current_location_id, :string, 3
      end
    end
    add_message "mobility.services.RetrieveDistanceMovedInFlightForMotorcycleRequest" do
      optional :motorcycle_id, :string, 1
      optional :current_flight_id, :string, 2
    end
    add_message "mobility.services.RetrieveDistanceMovedInFlightForMotorcycleResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.MotorcycleErrorResponse"
        optional :current_distance_id, :string, 3
      end
    end
  end
end

module Mobility
  module Services
    Motorcycle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Motorcycle").msgclass
    MotorcyclesList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.MotorcyclesList").msgclass
    MotorcycleSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.MotorcycleSuccessResponse").msgclass
    MotorcycleErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.MotorcycleErrorResponse").msgclass
    ListMotorcyclesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListMotorcyclesRequest").msgclass
    ListMotorcyclesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListMotorcyclesResponse").msgclass
    GetMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetMotorcycleRequest").msgclass
    GetMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetMotorcycleResponse").msgclass
    CreateMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateMotorcycleRequest").msgclass
    CreateMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateMotorcycleResponse").msgclass
    UpdateMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateMotorcycleRequest").msgclass
    UpdateMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateMotorcycleResponse").msgclass
    DeleteMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteMotorcycleRequest").msgclass
    DeleteMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteMotorcycleResponse").msgclass
    ReceiveBatteryForMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ReceiveBatteryForMotorcycleRequest").msgclass
    ReceiveBatteryForMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ReceiveBatteryForMotorcycleResponse").msgclass
    ReturnBatteryForMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ReturnBatteryForMotorcycleRequest").msgclass
    ReturnBatteryForMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ReturnBatteryForMotorcycleResponse").msgclass
    AssignFlightForMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AssignFlightForMotorcycleRequest").msgclass
    AssignFlightForMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AssignFlightForMotorcycleResponse").msgclass
    RetrieveCurrentFlightForMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentFlightForMotorcycleRequest").msgclass
    RetrieveCurrentFlightForMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentFlightForMotorcycleResponse").msgclass
    RetrieveCurrentLocationForMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentLocationForMotorcycleRequest").msgclass
    RetrieveCurrentLocationForMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveCurrentLocationForMotorcycleResponse").msgclass
    RetrieveDistanceMovedInFlightForMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveDistanceMovedInFlightForMotorcycleRequest").msgclass
    RetrieveDistanceMovedInFlightForMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.RetrieveDistanceMovedInFlightForMotorcycleResponse").msgclass
  end
end
