# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: motorcycle.proto for package 'mobility.services'

require 'grpc'
require_relative './motorcycle_pb'

module Mobility
  module Services
    module MotorcycleServices
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mobility.services.MotorcycleServices'

        rpc :ListMotorcycles, ::Mobility::Services::ListMotorcyclesRequest, ::Mobility::Services::ListMotorcyclesResponse
        rpc :GetMotorcycle, ::Mobility::Services::GetMotorcycleRequest, ::Mobility::Services::GetMotorcycleResponse
        rpc :CreateMotorcycle, ::Mobility::Services::CreateMotorcycleRequest, ::Mobility::Services::CreateMotorcycleResponse
        rpc :UpdateMotorcycle, ::Mobility::Services::UpdateMotorcycleRequest, ::Mobility::Services::UpdateMotorcycleResponse
        rpc :DeleteMotorcycle, ::Mobility::Services::DeleteMotorcycleRequest, ::Mobility::Services::DeleteMotorcycleResponse
        rpc :ReceiveBatteryForMotorcycle, ::Mobility::Services::ReceiveBatteryForMotorcycleRequest, ::Mobility::Services::ReceiveBatteryForMotorcycleResponse
        rpc :ReturnBatteryForMotorcycle, ::Mobility::Services::ReturnBatteryForMotorcycleRequest, ::Mobility::Services::ReturnBatteryForMotorcycleResponse
        rpc :AssignFlightForMotorcycle, ::Mobility::Services::AssignFlightForMotorcycleRequest, ::Mobility::Services::AssignFlightForMotorcycleResponse
        rpc :RetrieveCurrentFlightForMotorcycle, ::Mobility::Services::RetrieveCurrentFlightForMotorcycleRequest, ::Mobility::Services::RetrieveCurrentFlightForMotorcycleResponse
        rpc :RetrieveCurrentLocationForMotorcycle, ::Mobility::Services::RetrieveCurrentLocationForMotorcycleRequest, ::Mobility::Services::RetrieveCurrentLocationForMotorcycleResponse
        rpc :RetrieveDistanceMovedInFlightForMotorcycle, ::Mobility::Services::RetrieveDistanceMovedInFlightForMotorcycleRequest, ::Mobility::Services::RetrieveDistanceMovedInFlightForMotorcycleResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
