# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("notification.proto", :syntax => :proto3) do
    add_message "mobility.services.Notification" do
      optional :content, :string, 1
      optional :notification_id, :string, 2
      optional :created_at, :string, 3
      optional :received_at, :string, 4
      optional :viewed_at, :string, 5
      oneof :type do
        optional :admin_notification, :message, 6, "mobility.services.AdminNotification"
        optional :operator_notification, :message, 7, "mobility.services.OperatorNotification"
        optional :driver_notification, :message, 8, "mobility.services.DriverNotification"
      end
    end
    add_message "mobility.services.AdminNotification" do
      optional :id, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.OperatorNotification" do
      optional :id, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.DriverNotification" do
      optional :id, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.NotificationsList" do
      repeated :notifications, :message, 1, "mobility.services.Notification"
    end
    add_message "mobility.services.Success" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.Error" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListNotificationsRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListNotificationsResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :notifications_list, :message, 3, "mobility.services.NotificationsList"
      end
    end
    add_message "mobility.services.GetNotificationRequest" do
      optional :notification_id, :string, 1
    end
    add_message "mobility.services.GetNotificationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :notification, :message, 3, "mobility.services.Notification"
      end
    end
    add_message "mobility.services.CreateNotificationRequest" do
      optional :notification, :message, 1, "mobility.services.Notification"
    end
    add_message "mobility.services.CreateNotificationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :notification, :message, 3, "mobility.services.Notification"
      end
    end
    add_message "mobility.services.UpdateNotificationRequest" do
      optional :notification, :message, 1, "mobility.services.Notification"
    end
    add_message "mobility.services.UpdateNotificationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :notification, :message, 3, "mobility.services.Notification"
      end
    end
    add_message "mobility.services.DeleteNotificationRequest" do
      optional :notification_id, :string, 1
    end
    add_message "mobility.services.DeleteNotificationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
  end
end

module Mobility
  module Services
    Notification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Notification").msgclass
    AdminNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.AdminNotification").msgclass
    OperatorNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.OperatorNotification").msgclass
    DriverNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DriverNotification").msgclass
    NotificationsList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.NotificationsList").msgclass
    Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Success").msgclass
    Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Error").msgclass
    ListNotificationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListNotificationsRequest").msgclass
    ListNotificationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListNotificationsResponse").msgclass
    GetNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetNotificationRequest").msgclass
    GetNotificationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetNotificationResponse").msgclass
    CreateNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateNotificationRequest").msgclass
    CreateNotificationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateNotificationResponse").msgclass
    UpdateNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateNotificationRequest").msgclass
    UpdateNotificationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateNotificationResponse").msgclass
    DeleteNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteNotificationRequest").msgclass
    DeleteNotificationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteNotificationResponse").msgclass
  end
end
