# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("operator.proto", :syntax => :proto3) do
    add_message "mobility.services.Operator" do
      optional :operator_id, :string, 1
      optional :name, :string, 2
      optional :identification, :string, 3
      optional :phone_number, :string, 4
      optional :created_at, :string, 5
      optional :modified_at, :string, 6
      optional :deleted_at, :string, 7
      optional :current_station_id, :string, 8
    end
    add_message "mobility.services.OperatorsList" do
      repeated :operators, :message, 1, "mobility.services.Operator"
    end
    add_message "mobility.services.Success" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.Error" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListOperatorsRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListOperatorsResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :operators_list, :message, 3, "mobility.services.OperatorsList"
      end
    end
    add_message "mobility.services.GetOperatorRequest" do
      optional :operator_id, :string, 1
    end
    add_message "mobility.services.GetOperatorResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :operator, :message, 3, "mobility.services.Operator"
      end
    end
    add_message "mobility.services.CreateOperatorRequest" do
      optional :operator, :message, 1, "mobility.services.Operator"
    end
    add_message "mobility.services.CreateOperatorResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :operator, :message, 3, "mobility.services.Operator"
      end
    end
    add_message "mobility.services.UpdateOperatorRequest" do
      optional :operator, :message, 1, "mobility.services.Operator"
    end
    add_message "mobility.services.UpdateOperatorResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :operator, :message, 3, "mobility.services.Operator"
      end
    end
    add_message "mobility.services.DeleteOperatorRequest" do
      optional :operator_id, :string, 1
    end
    add_message "mobility.services.DeleteOperatorResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.SignInToStationRequest" do
      optional :operator_id, :string, 1
      optional :station_id, :string, 2
    end
    add_message "mobility.services.SignInToStationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.InitiateFlightRequest" do
      optional :initiating_operator_id, :string, 1
      optional :initiating_station_id, :string, 2
    end
    add_message "mobility.services.InitiateFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.TerminateFlightRequest" do
      optional :terminating_operator_id, :string, 1
      optional :terminating_station_id, :string, 2
      optional :flight_id, :string, 3
    end
    add_message "mobility.services.TerminateFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.InitiateSwapRequest" do
      optional :operator_id, :string, 1
      optional :incoming_flight_id, :string, 2
      optional :outgoing_flight_id, :string, 3
      optional :incoming_battery_id, :string, 4
      optional :outgoing_battery_id, :string, 5
    end
    add_message "mobility.services.InitiateSwapResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.InitiatePaymentForFlightRequest" do
      optional :operator_id, :string, 1
      optional :flight_id, :string, 2
    end
    add_message "mobility.services.InitiatePaymentForFlightResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
  end
end

module Mobility
  module Services
    Operator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Operator").msgclass
    OperatorsList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.OperatorsList").msgclass
    Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Success").msgclass
    Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Error").msgclass
    ListOperatorsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListOperatorsRequest").msgclass
    ListOperatorsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListOperatorsResponse").msgclass
    GetOperatorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetOperatorRequest").msgclass
    GetOperatorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetOperatorResponse").msgclass
    CreateOperatorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateOperatorRequest").msgclass
    CreateOperatorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateOperatorResponse").msgclass
    UpdateOperatorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateOperatorRequest").msgclass
    UpdateOperatorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateOperatorResponse").msgclass
    DeleteOperatorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteOperatorRequest").msgclass
    DeleteOperatorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteOperatorResponse").msgclass
    SignInToStationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SignInToStationRequest").msgclass
    SignInToStationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SignInToStationResponse").msgclass
    InitiateFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.InitiateFlightRequest").msgclass
    InitiateFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.InitiateFlightResponse").msgclass
    TerminateFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.TerminateFlightRequest").msgclass
    TerminateFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.TerminateFlightResponse").msgclass
    InitiateSwapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.InitiateSwapRequest").msgclass
    InitiateSwapResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.InitiateSwapResponse").msgclass
    InitiatePaymentForFlightRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.InitiatePaymentForFlightRequest").msgclass
    InitiatePaymentForFlightResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.InitiatePaymentForFlightResponse").msgclass
  end
end
