# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: payment.proto for package 'mobility.services'

require 'grpc'
require 'payment_pb'

module Mobility
  module Services
    module PaymentServices
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mobility.services.PaymentServices'

        rpc :ListPayments, ::Mobility::Services::ListPaymentsRequest, ::Mobility::Services::ListPaymentsResponse
        rpc :GetPayment, ::Mobility::Services::GetPaymentRequest, ::Mobility::Services::GetPaymentResponse
        rpc :CreatePayment, ::Mobility::Services::CreatePaymentRequest, ::Mobility::Services::CreatePaymentResponse
        rpc :UpdatePayment, ::Mobility::Services::UpdatePaymentRequest, ::Mobility::Services::UpdatePaymentResponse
        rpc :DeletePayment, ::Mobility::Services::DeletePaymentRequest, ::Mobility::Services::DeletePaymentResponse
        rpc :CollectPaymentForFlightID, ::Mobility::Services::CollectPaymentForFlightIDRequest, ::Mobility::Services::CollectPaymentForFlightIDResponse
        rpc :CheckIfPaymentDone, ::Mobility::Services::CheckIfPaymentDoneRequest, ::Mobility::Services::CheckIfPaymentDoneResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
