# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("payment.proto", :syntax => :proto3) do
    add_message "mobility.services.Payment" do
      optional :payment_id, :string, 1
      optional :flight_id, :string, 2
      optional :amount, :string, 3
      optional :currency, :string, 4
      optional :created_at, :string, 5
      optional :modified_at, :string, 6
      optional :fulfilled_on, :string, 7
      optional :fulfilled_by_operator_id, :string, 8
      optional :paid_by_driver_id, :string, 9
      optional :status, :bool, 10
    end
    add_message "mobility.services.PaymentsList" do
      repeated :payments, :message, 1, "mobility.services.Payment"
    end
    add_message "mobility.services.PaymentSuccessResponse" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.PaymentErrorResponse" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListPaymentsRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListPaymentsResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.PaymentErrorResponse"
        optional :payments_list, :message, 3, "mobility.services.PaymentsList"
      end
    end
    add_message "mobility.services.GetPaymentRequest" do
      optional :payment_id, :string, 1
    end
    add_message "mobility.services.GetPaymentResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.PaymentErrorResponse"
        optional :payment, :message, 3, "mobility.services.Payment"
      end
    end
    add_message "mobility.services.CreatePaymentRequest" do
      optional :payment, :message, 1, "mobility.services.Payment"
    end
    add_message "mobility.services.CreatePaymentResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.PaymentErrorResponse"
        optional :payment, :message, 3, "mobility.services.Payment"
      end
    end
    add_message "mobility.services.UpdatePaymentRequest" do
      optional :payment, :message, 1, "mobility.services.Payment"
    end
    add_message "mobility.services.UpdatePaymentResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.PaymentErrorResponse"
        optional :payment, :message, 3, "mobility.services.Payment"
      end
    end
    add_message "mobility.services.DeletePaymentRequest" do
      optional :payment_id, :string, 1
    end
    add_message "mobility.services.DeletePaymentResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.PaymentErrorResponse"
        optional :success, :message, 3, "mobility.services.PaymentSuccessResponse"
      end
    end
    add_message "mobility.services.CollectPaymentForFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.CollectPaymentForFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.PaymentErrorResponse"
        optional :payment, :message, 3, "mobility.services.Payment"
      end
    end
    add_message "mobility.services.CheckIfPaymentDoneRequest" do
      optional :payment_id, :string, 1
    end
    add_message "mobility.services.CheckIfPaymentDoneResponse" do
      optional :status, :bool, 1
    end
  end
end

module Mobility
  module Services
    Payment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Payment").msgclass
    PaymentsList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.PaymentsList").msgclass
    PaymentSuccessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.PaymentSuccessResponse").msgclass
    PaymentErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.PaymentErrorResponse").msgclass
    ListPaymentsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListPaymentsRequest").msgclass
    ListPaymentsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListPaymentsResponse").msgclass
    GetPaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetPaymentRequest").msgclass
    GetPaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetPaymentResponse").msgclass
    CreatePaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreatePaymentRequest").msgclass
    CreatePaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreatePaymentResponse").msgclass
    UpdatePaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdatePaymentRequest").msgclass
    UpdatePaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdatePaymentResponse").msgclass
    DeletePaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeletePaymentRequest").msgclass
    DeletePaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeletePaymentResponse").msgclass
    CollectPaymentForFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CollectPaymentForFlightIDRequest").msgclass
    CollectPaymentForFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CollectPaymentForFlightIDResponse").msgclass
    CheckIfPaymentDoneRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CheckIfPaymentDoneRequest").msgclass
    CheckIfPaymentDoneResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CheckIfPaymentDoneResponse").msgclass
  end
end
