# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("station.proto", :syntax => :proto3) do
    add_message "mobility.services.Station" do
      optional :station_id, :string, 1
      optional :name, :string, 2
      optional :location, :string, 3
      optional :created_at, :string, 4
      optional :modified_at, :string, 5
      optional :deleted_at, :string, 6
      optional :battery_count, :int32, 7
      optional :charging_ports_count, :int32, 8
    end
    add_message "mobility.services.StationsList" do
      repeated :stations, :message, 1, "mobility.services.Station"
    end
    add_message "mobility.services.Success" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.Error" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListStationsRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListStationsResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :stations_list, :message, 3, "mobility.services.StationsList"
      end
    end
    add_message "mobility.services.GetStationRequest" do
      optional :station_id, :string, 1
    end
    add_message "mobility.services.GetStationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :station, :message, 3, "mobility.services.Station"
      end
    end
    add_message "mobility.services.CreateStationRequest" do
      optional :station, :message, 1, "mobility.services.Station"
    end
    add_message "mobility.services.CreateStationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :station, :message, 3, "mobility.services.Station"
      end
    end
    add_message "mobility.services.UpdateStationRequest" do
      optional :station, :message, 1, "mobility.services.Station"
    end
    add_message "mobility.services.UpdateStationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :station, :message, 3, "mobility.services.Station"
      end
    end
    add_message "mobility.services.DeleteStationRequest" do
      optional :station_id, :string, 1
    end
    add_message "mobility.services.DeleteStationResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.GetBatterySupplyForStationRequest" do
      optional :station_id, :string, 1
    end
    add_message "mobility.services.GetBatterySupplyForStationResponse" do
      optional :battery_count, :int32, 1
    end
    add_message "mobility.services.GetStationAvailableChargingPortsRequest" do
      optional :station_id, :string, 1
    end
    add_message "mobility.services.GetStationAvailableChargingPortsResponse" do
      optional :charging_ports_count, :int32, 1
    end
    add_message "mobility.services.GetStationDistanceRelativeToMotorcycleRequest" do
      optional :station_id, :string, 1
      optional :motorcycle_id, :string, 2
    end
    add_message "mobility.services.GetStationDistanceRelativeToMotorcycleResponse" do
      optional :distance_apart, :int32, 1
    end
  end
end

module Mobility
  module Services
    Station = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Station").msgclass
    StationsList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.StationsList").msgclass
    Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Success").msgclass
    Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Error").msgclass
    ListStationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListStationsRequest").msgclass
    ListStationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListStationsResponse").msgclass
    GetStationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetStationRequest").msgclass
    GetStationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetStationResponse").msgclass
    CreateStationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateStationRequest").msgclass
    CreateStationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateStationResponse").msgclass
    UpdateStationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateStationRequest").msgclass
    UpdateStationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateStationResponse").msgclass
    DeleteStationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteStationRequest").msgclass
    DeleteStationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteStationResponse").msgclass
    GetBatterySupplyForStationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetBatterySupplyForStationRequest").msgclass
    GetBatterySupplyForStationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetBatterySupplyForStationResponse").msgclass
    GetStationAvailableChargingPortsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetStationAvailableChargingPortsRequest").msgclass
    GetStationAvailableChargingPortsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetStationAvailableChargingPortsResponse").msgclass
    GetStationDistanceRelativeToMotorcycleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetStationDistanceRelativeToMotorcycleRequest").msgclass
    GetStationDistanceRelativeToMotorcycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetStationDistanceRelativeToMotorcycleResponse").msgclass
  end
end
