# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: station.proto for package 'mobility.services'

require 'grpc'
require_relative './station_pb'

module Mobility
  module Services
    module StationServices
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mobility.services.StationServices'

        rpc :ListStations, ::Mobility::Services::ListStationsRequest, ::Mobility::Services::ListStationsResponse
        rpc :GetStation, ::Mobility::Services::GetStationRequest, ::Mobility::Services::GetStationResponse
        rpc :CreateStation, ::Mobility::Services::CreateStationRequest, ::Mobility::Services::CreateStationResponse
        rpc :UpdateStation, ::Mobility::Services::UpdateStationRequest, ::Mobility::Services::UpdateStationResponse
        rpc :DeleteStation, ::Mobility::Services::DeleteStationRequest, ::Mobility::Services::DeleteStationResponse
        rpc :GetBatterySupplyForStation, ::Mobility::Services::GetBatterySupplyForStationRequest, ::Mobility::Services::GetBatterySupplyForStationResponse
        rpc :GetStationAvailableChargingPorts, ::Mobility::Services::GetStationAvailableChargingPortsRequest, ::Mobility::Services::GetStationAvailableChargingPortsResponse
        rpc :GetStationDistanceRelativeToMotorcycle, ::Mobility::Services::GetStationDistanceRelativeToMotorcycleRequest, ::Mobility::Services::GetStationDistanceRelativeToMotorcycleResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
