# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: swap.proto for package 'mobility.services'

require 'grpc'
require 'swap_pb'

module Mobility
  module Services
    module SwapServices
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'mobility.services.SwapServices'

        rpc :ListSwaps, ::Mobility::Services::ListSwapsRequest, ::Mobility::Services::ListSwapsResponse
        rpc :GetSwap, ::Mobility::Services::GetSwapRequest, ::Mobility::Services::GetSwapResponse
        rpc :CreateSwap, ::Mobility::Services::CreateSwapRequest, ::Mobility::Services::CreateSwapResponse
        rpc :UpdateSwap, ::Mobility::Services::UpdateSwapRequest, ::Mobility::Services::UpdateSwapResponse
        rpc :DeleteSwap, ::Mobility::Services::DeleteSwapRequest, ::Mobility::Services::DeleteSwapResponse
        rpc :SearchSwapByOperatorID, ::Mobility::Services::SearchSwapByOperatorIDRequest, ::Mobility::Services::SearchSwapByOperatorIDResponse
        rpc :SearchSwapByBatteryID, ::Mobility::Services::SearchSwapByBatteryIDRequest, ::Mobility::Services::SearchSwapByBatteryIDResponse
        rpc :SearchSwapByFlightID, ::Mobility::Services::SearchSwapByFlightIDRequest, ::Mobility::Services::SearchSwapByFlightIDResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
