# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swap.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("swap.proto", :syntax => :proto3) do
    add_message "mobility.services.Swap" do
      optional :swap_id, :string, 1
      optional :operator_id, :string, 2
      optional :incoming_flight_id, :string, 3
      optional :outgoing_flight_id, :string, 4
      optional :incoming_battery_id, :string, 5
      optional :outgoing_battery_id, :string, 6
      optional :created_at, :string, 7
    end
    add_message "mobility.services.SwapsList" do
      repeated :swaps, :message, 1, "mobility.services.Swap"
    end
    add_message "mobility.services.Success" do
      optional :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.Error" do
      repeated :content, :string, 1
      optional :type, :string, 2
    end
    add_message "mobility.services.ListSwapsRequest" do
      optional :page_size, :int32, 1
    end
    add_message "mobility.services.ListSwapsResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :swaps_list, :message, 3, "mobility.services.SwapsList"
      end
    end
    add_message "mobility.services.GetSwapRequest" do
      optional :swap_id, :string, 1
    end
    add_message "mobility.services.GetSwapResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :swap, :message, 3, "mobility.services.Swap"
      end
    end
    add_message "mobility.services.CreateSwapRequest" do
      optional :swap, :message, 1, "mobility.services.Swap"
    end
    add_message "mobility.services.CreateSwapResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :swap, :message, 3, "mobility.services.Swap"
      end
    end
    add_message "mobility.services.UpdateSwapRequest" do
      optional :swap, :message, 1, "mobility.services.Swap"
    end
    add_message "mobility.services.UpdateSwapResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :swap, :message, 3, "mobility.services.Swap"
      end
    end
    add_message "mobility.services.DeleteSwapRequest" do
      optional :swap_id, :string, 1
    end
    add_message "mobility.services.DeleteSwapResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :success, :message, 3, "mobility.services.Success"
      end
    end
    add_message "mobility.services.SearchSwapByOperatorIDRequest" do
      optional :operator_id, :string, 1
    end
    add_message "mobility.services.SearchSwapByOperatorIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :swaps_list, :message, 3, "mobility.services.SwapsList"
      end
    end
    add_message "mobility.services.SearchSwapByBatteryIDRequest" do
      optional :battery_id, :string, 1
    end
    add_message "mobility.services.SearchSwapByBatteryIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :swaps_list, :message, 3, "mobility.services.SwapsList"
      end
    end
    add_message "mobility.services.SearchSwapByFlightIDRequest" do
      optional :flight_id, :string, 1
    end
    add_message "mobility.services.SearchSwapByFlightIDResponse" do
      optional :successful, :bool, 1
      oneof :result do
        optional :error, :message, 2, "mobility.services.Error"
        optional :swaps_list, :message, 3, "mobility.services.SwapsList"
      end
    end
  end
end

module Mobility
  module Services
    Swap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Swap").msgclass
    SwapsList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SwapsList").msgclass
    Success = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Success").msgclass
    Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.Error").msgclass
    ListSwapsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListSwapsRequest").msgclass
    ListSwapsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.ListSwapsResponse").msgclass
    GetSwapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetSwapRequest").msgclass
    GetSwapResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.GetSwapResponse").msgclass
    CreateSwapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateSwapRequest").msgclass
    CreateSwapResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.CreateSwapResponse").msgclass
    UpdateSwapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateSwapRequest").msgclass
    UpdateSwapResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.UpdateSwapResponse").msgclass
    DeleteSwapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteSwapRequest").msgclass
    DeleteSwapResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.DeleteSwapResponse").msgclass
    SearchSwapByOperatorIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SearchSwapByOperatorIDRequest").msgclass
    SearchSwapByOperatorIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SearchSwapByOperatorIDResponse").msgclass
    SearchSwapByBatteryIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SearchSwapByBatteryIDRequest").msgclass
    SearchSwapByBatteryIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SearchSwapByBatteryIDResponse").msgclass
    SearchSwapByFlightIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SearchSwapByFlightIDRequest").msgclass
    SearchSwapByFlightIDResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mobility.services.SearchSwapByFlightIDResponse").msgclass
  end
end
