version: '3.9'
services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        runner: "docker"
    ports:
      - '2181:2181'
      - '9092:9092'
    volumes:
      - .:/event-gateway-kafka
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.event-gateway
      args:
        runner: "gateway"
    ports:
      - '3707:3707'
    volumes:
      - .:/event-gateway