version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        runner: "web"
    command: bundle exec rackup --host 0.0.0.0 -p 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/frontend-admin